export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_END = 'GET_CATEGORIES_END';
export const GET_ITEMS_FOR_CATEGORY_BEGIN = "GET_ITEMS_FOR_CATEGORY_BEGIN";
export const GET_ITEMS_FOR_CATEGORY_END = "GET_ITEMS_FOR_CATEGORY_END";
export const SEARCH_TERM_CHANGED = "SEARCH_TERM_CHANGED";